-- The base game's worlds (zones), grouped by playset. Generated from
-- gamedb/core/zonelist.lua (startup2 archive), Records.Zones. Left out: frontend
-- (Go to main menu covers it), zones flagged out of the shipping or consumer
-- build, and what is not base game -- Marvel Battlegrounds and Finding Dory
-- (1.05/1.06), Moana, Barbados and the HoloDeck tests, which are Disney
-- Infinity Complete's. Sub-zones remain; the game may refuse some of them.

return {
    { title = "Toy Box", worlds = {
        "TBB_Combat_Population",
        "TBX_Adventure_Enemies",
        "TBX_Adventure_Hub",
        "TBX_Adventure_Inc",
        "TBX_Adventure_LR",
        "TBX_Adventure_Marvel",
        "TBX_Adventure_Pirates",
        "TBX_Adventure_SW",
        "TBX_Buddy1",
        "TBX_Buddy2",
        "TBX_Buddy3",
        "TBX_Building_Logic1",
        "TBX_Building_Logic2",
        "TBX_Building_Logic3",
        "TBX_Building_Logic4",
        "TBX_Building_Logic5",
        "TBX_Combat1",
        "TBX_Combat2",
        "TBX_Combat3",
        "TBX_Combat4",
        "TBX_Combat5",
        "TBX_HoH_SW",
        "TBX_IN3_DailyChallenge",
        "TBX_IN3_Skirmish",
        "TBX_Launch",
        "TBX_Launch_Logic",
        "TBX_Onboard",
        "TBX_Onboard_Arcade_inside",
        "TBX_Onboard_Buddy",
        "TBX_Onboard_Build",
        "TBX_Onboard_Build_Open",
        "TBX_Onboard_UGC",
        "TBX_Platform_A",
        "TBX_Platform_B",
        "TBX_Platform_D",
        "TBX_Platform_E",
        "TBX_Platform_G",
        "TBX_Transition",
        "TBX_VehicleLand1",
        "TBX_VehicleLand2",
        "TBX_VehicleLand3",
        "TBX_VehicleLand4",
        "TBX_VehicleLand5",
    } },
    { title = "Toy Box worlds", worlds = {
        "RumpusRoom",
        "RumpusRoom_Blank",
        "RumpusRoom_Bridges",
        "RumpusRoom_Cars",
        "RumpusRoom_Dragon",
        "RumpusRoom_HH",
        "RumpusRoom_HH2_Marvel",
        "RumpusRoom_Hills",
        "RumpusRoom_incworld",
        "RumpusRoom_Islands",
        "RumpusRoom_LR",
        "RumpusRoom_MU",
        "rumpusroom_newcity",
        "rumpusroom_newracetrack",
        "RumpusRoom_NewTerrain",
        "rumpusroom_newtreehouse",
        "RumpusRoom_Pirates",
        "RumpusRoom_Simple",
        "RumpusRoom_TBI_Blank",
        "RumpusRoom_TBI_Home",
        "RumpusRoom_ToyStory",
    } },
    { title = "Toy Box Speedway", worlds = {
        "KRT_ALDN_SpdWay",
        "KRT_BHSX_SpdWay",
        "KRT_FRZN_AlpSpy",
        "KRT_GVTY_SpdWay",
        "KRT_KNWR_SpdWay",
        "KRT_MONS_DorStr",
        "KRT_NB4C_SpdWay",
        "KRT_TATO_SpdWay",
        "KRT_TBSW_RacHub",
        "KRT_WKRH_SugRsh",
    } },
    { title = "Rise Against the Empire", worlds = {
        "EMP_DeathStar1_Details",
        "EMP_DeathStar1_Interior",
        "EMP_DeathStar2_Details",
        "EMP_DeathStar2_Interior",
        "EMP_Endor_Details",
        "EMP_Endor_Main",
        "EMP_Endor_Space",
        "EMP_Endor_Space_Missions",
        "EMP_Hoth_Details",
        "EMP_Hoth_Escape",
        "EMP_Hoth_Main",
        "EMP_Hoth_Space",
        "EMP_Hoth_Space_Missions",
        "EMP_Master",
        "EMP_Tatooine_Details",
        "EMP_Tatooine_Main",
        "EMP_Tatooine_Space",
        "EMP_Tatooine_Space_Missions",
        "EMP_Tatooine_Tutorial",
    } },
    { title = "Twilight of the Republic", worlds = {
        "TCW_Chal01_DeathStar",
        "TCW_Chal02_Mining",
        "TCW_Chal03_IceFire",
        "TCW_Chal04_Rock",
        "TCW_COR_SpeedChaseExpendable",
        "TCW_Coruscant_Arena",
        "TCW_Coruscant_CITY",
        "TCW_Coruscant_Jedi_Temple",
        "TCW_Coruscant_MASTER",
        "TCW_Coruscant_Moon1_Details",
        "TCW_Coruscant_Moon1_Tunnel",
        "TCW_Coruscant_Playground",
        "TCW_Coruscant_SPACE",
        "TCW_Coruscant_SPACE_Details",
        "TCW_Coruscant_TERRAIN",
        "TCW_Coruscant_Tunnels",
        "TCW_DarthMaulFight",
        "TCW_Geonosis_CITY",
        "TCW_Geonosis_MASTER",
        "TCW_Geonosis_SPACE",
        "TCW_Geonosis_SPACE_Details",
        "TCW_Geonosis_TERRAIN",
        "TCW_Jabba_Box",
        "TCW_Master",
        "TCW_Missions_MASTER",
        "TCW_Naboo_MASTER",
        "TCW_Naboo_Moon1_Details",
        "TCW_Naboo_Moon1_Tunnel",
        "TCW_Naboo_SPACE",
        "TCW_Naboo_SPACE_Details",
        "TCW_Naboo_TERRAIN",
        "TCW_SpaceMissions_MASTER",
        "TCW_Tatooine_MASTER",
        "TCW_Tatooine_Moon1_Details",
        "TCW_Tatooine_Moon1_Tunnel",
        "TCW_Tatooine_PodRace",
        "TCW_Tatooine_SPACE",
        "TCW_Tatooine_SPACE_Details",
        "TCW_Tatooine_TERRAIN",
    } },
    { title = "The Force Awakens", worlds = {
        "PSX_Arcade",
        "PSX_Arcade_01",
        "PSX_Intro",
        "PSX_L1_Moon1_Details",
        "PSX_L1_Moon1_Tunnel",
        "PSX_L1_Planet_Details",
        "PSX_L1_Planet_Escape",
        "PSX_L1_Planet_Main",
        "PSX_L1_Space",
        "PSX_L1_Space_Missions",
        "PSX_L2_Planet_Details",
        "PSX_L2_Planet_Main",
        "PSX_L2_Space",
        "PSX_L3_Moon1_Details",
        "PSX_L3_Moon1_Tunnel",
        "PSX_L3_Planet_Details",
        "PSX_L3_Planet_Main",
        "PSX_L3_Space",
        "PSX_L3_Space_Missions",
        "PSX_L4_Planet_Details",
        "PSX_L4_Planet_Main",
        "PSX_L4_Space",
        "PSX_L4_Space_Missions",
        "PSX_Master",
    } },
    { title = "Inside Out", worlds = {
        "OUT_FinalBoss",
        "OUT_HQHub",
        "OUT_Intro1",
        "OUT_L1_S1",
        "OUT_L1_S2",
        "OUT_L1_S3",
        "OUT_L2_S1",
        "OUT_L2_S2",
        "OUT_L2_S3",
        "OUT_L3_S1",
        "OUT_L3_S2",
        "OUT_L3_S3",
        "OUT_L4_S1",
        "OUT_L4_S2",
        "OUT_L4_S3",
        "OUT_L5_S1",
        "OUT_L5_S2",
        "OUT_L5_S3",
        "OUT_L6_S1",
        "OUT_L6_S2",
        "OUT_L6_S3",
        "OUT_L7_S1",
        "OUT_L7_S2",
        "OUT_L7_S3",
        "OUT_L8_S1",
        "OUT_L8_S2",
        "OUT_L8_S3",
        "OUT_L9_S1",
        "OUT_L9_S2",
        "OUT_L9_S3",
        "OUT_Master",
    } }
}
